[tool.poetry]
name = "langgraph-showcase"
version = "1.0.0"
description = "Guided tour of the Aion platform features, built with LangGraph"
authors = ["Terminal Research Team <support@terminal.exchange>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
#aionto-sdk= { git = "https://github.com/Terminal-Research/aion-python-sdk", branch = "main", extras = ["langgraph-server"] }
aionto-sdk = { git = "https://github.com/Terminal-Research/aion-python-sdk", branch = "features/single-package", extras = ["langgraph-server"] }

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-asyncio = "^0.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
